// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjtx_siRkpEXG3ee1VqN8sb_BjpvtF_LU',
    appId: '1:706404710263:web:ef137c413672b796629372',
    messagingSenderId: '706404710263',
    projectId: 'app-fincas',
    authDomain: 'app-fincas.firebaseapp.com',
    storageBucket: 'app-fincas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvvyKTigWjrflO-Lbpqad4O71xm0yyCnc',
    appId: '1:706404710263:android:0adf24f2ec0c326a629372',
    messagingSenderId: '706404710263',
    projectId: 'app-fincas',
    storageBucket: 'app-fincas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtWjpa-FwJ6QuqU6Ygftwfn-wrKwBTmT8',
    appId: '1:706404710263:ios:61d621e23debea92629372',
    messagingSenderId: '706404710263',
    projectId: 'app-fincas',
    storageBucket: 'app-fincas.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtWjpa-FwJ6QuqU6Ygftwfn-wrKwBTmT8',
    appId: '1:706404710263:ios:8e0732a7c4eaa331629372',
    messagingSenderId: '706404710263',
    projectId: 'app-fincas',
    storageBucket: 'app-fincas.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
