// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApdKnQmEGE0qF-7tZSq2RgkHCy8MPpicw',
    appId: '1:805633383649:web:d52bf89168d07a96dc6ba0',
    messagingSenderId: '805633383649',
    projectId: 'fincas-app',
    authDomain: 'fincas-app.firebaseapp.com',
    storageBucket: 'fincas-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoizb5oJmM1KWbujH1M-N5210rVCvnfv8',
    appId: '1:805633383649:android:209c38daaff9d8e4dc6ba0',
    messagingSenderId: '805633383649',
    projectId: 'fincas-app',
    storageBucket: 'fincas-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATXN4Th4McTrs8VR3bhH6qf21xoUgbHbU',
    appId: '1:805633383649:ios:ff80e6fc65456e61dc6ba0',
    messagingSenderId: '805633383649',
    projectId: 'fincas-app',
    storageBucket: 'fincas-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATXN4Th4McTrs8VR3bhH6qf21xoUgbHbU',
    appId: '1:805633383649:ios:c47ab7b7279cee63dc6ba0',
    messagingSenderId: '805633383649',
    projectId: 'fincas-app',
    storageBucket: 'fincas-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
